Update font-awesome icons
lucyparsons/OpenOversight pull request #1076
Opened 2023-12-11 21:59 UTC by michplunkett

## Description of Changes
This updates font-awesome to version 6.

## Screenshots (if appropriate)
Coming soon

## Tests and linting
 - [ ] This branch is up-to-date with the `develop` branch.
 - [ ] `pytest` passes on my local development environment.
 - [ ] `pre-commit` passes on my local development environment.

2023-12-12 03:45 UTC, michplunkett commented on OpenOversight/app/templates/label_data.html
> -          <div class="col-lg-4 horizontal-padding""> <span class="fa fa-users fa-2x"></span>
Addressed the double `""` at the end of the `div` above this message, so there was a lot of formatting done around it.

2023-12-12 03:45 UTC, michplunkett commented on OpenOversight/app/templates/label_data.html
> -        <div class="col-lg-4 horizontal-padding"">
Addressed the double `""` at the end of the `div` above this message, so there was a lot of formatting done around it.

2023-12-18 05:25 UTC, sea-kelp requested changes
Can we use the regular or light variants of fontawesome instead of solid? The pencil-square and trash icons especially seem a bit dark on the site.

**label_data.html**
1. These three icons should use `fa-solid` instead of `fa` here
2. `fa-picture-o` doesn't seem to exist in the new version
https://github.com/lucyparsons/OpenOversight/blob/037debbdc0e4c36f8ef33e7d070e51465160d6a9/OpenOversight/app/templates/label_data.html#L99-L108

**officer_assignment_history.html**
These styles should use `fa-solid` instead of `fa`
https://github.com/lucyparsons/OpenOversight/blob/037debbdc0e4c36f8ef33e7d070e51465160d6a9/OpenOversight/app/templates/partials/officer_assignment_history.html#L47

2023-12-18 16:38 UTC, michplunkett commented
I gotchu, @sea-kelp! I'll make the changes sometime within the next two-three days.

2023-12-19 02:43 UTC, michplunkett commented on OpenOversight/app/templates/label_data.html
> +              <span class="fa-solid fa-image fa-2x"></span>
<img width="1191" alt="Screenshot 2023-12-18 at 9 41 55 PM" src="https://github.com/lucyparsons/OpenOversight/assets/5885605/8a677bbc-6f8c-4602-aa80-9372b0a5e37c">

Here go, @sea-kelp!

2023-12-19 02:45 UTC, michplunkett commented on OpenOversight/app/templates/partials/officer_assignment_history.html
> +              <i class="fa-solid fa-pencil-square" aria-hidden="true"></i>
We're good with the `fa-solid` here, @sea-kelp.

2023-12-19 20:40 UTC, sea-kelp approved these changes
Looks great! Thank you for making those changes

2023-12-19 20:42 UTC, merged